repository_type: pipeline
lint:
  files_exist:
    - assets/multiqc_config.yml
    - assets/nf-core-ensemblgenedownload_logo_light.png
    - conf/igenomes.config
    - docs/images/nf-core-ensemblgenedownload_logo_light.png
    - docs/images/nf-core-ensemblgenedownload_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
  files_unchanged:
    - LICENSE
    - .github/CONTRIBUTING.md
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/workflows/linting.yml
    - assets/sendmail_template.txt
    - lib/NfcoreTemplate.groovy
    - .github/workflows/branch.yml
  nextflow_config:
    - manifest.name
    - manifest.homePage
